// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *EnvScanOp) InputFields() map[string]any {
	return map[string]any {
		"GoFiles": &op.GoFiles,
	}
}

func (op *EnvScanOp) OutputFields() map[string]any {
	return map[string]any {
		"RequiredEnvVars": &op.RequiredEnvVars,
	}
}

func (op *EnvScanOp) SetInputField(field string, value any) error {
	switch field {
	case "GoFiles":
		if val, ok := value.(*string); ok {
			op.GoFiles = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *EnvScanOp) ResetFields() {
	var zeroGoFiles *string
	op.GoFiles = zeroGoFiles
	
	var zeroRequiredEnvVars string
	op.RequiredEnvVars = zeroRequiredEnvVars
	
}