// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *CodegenOp) InputFields() map[string]any {
	return map[string]any {
		"TempDir": &op.TempDir,
	}
}

func (op *CodegenOp) OutputFields() map[string]any {
	return map[string]any {
		"ExitCode": &op.ExitCode,"Stderr": &op.Stderr,
	}
}

func (op *CodegenOp) SetInputField(field string, value any) error {
	switch field {
	case "TempDir":
		if val, ok := value.(*string); ok {
			op.TempDir = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *CodegenOp) ResetFields() {
	var zeroTempDir *string
	op.TempDir = zeroTempDir
	
	var zeroExitCode int
	op.ExitCode = zeroExitCode
	var zeroStderr string
	op.Stderr = zeroStderr
	
}