// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *MCPBManifestAIOp) InputFields() map[string]any {
	return map[string]any {
		"Prompt": &op.Prompt,"ApprovedDesign": &op.ApprovedDesign,"BinPath": &op.BinPath,
	}
}

func (op *MCPBManifestAIOp) OutputFields() map[string]any {
	return map[string]any {
		"Name": &op.Name,"DisplayName": &op.DisplayName,"Description": &op.Description,
	}
}

func (op *MCPBManifestAIOp) SetInputField(field string, value any) error {
	switch field {
	case "Prompt":
		if val, ok := value.(*string); ok {
			op.Prompt = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "ApprovedDesign":
		if val, ok := value.(*string); ok {
			op.ApprovedDesign = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "BinPath":
		if val, ok := value.(*string); ok {
			op.BinPath = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *MCPBManifestAIOp) ResetFields() {
	var zeroPrompt *string
	op.Prompt = zeroPrompt
	var zeroApprovedDesign *string
	op.ApprovedDesign = zeroApprovedDesign
	var zeroBinPath *string
	op.BinPath = zeroBinPath
	
	var zeroName string
	op.Name = zeroName
	var zeroDisplayName string
	op.DisplayName = zeroDisplayName
	var zeroDescription string
	op.Description = zeroDescription
	
}