// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *FallbackOp) InputFields() map[string]any {
	return map[string]any {
		"Prompt": &op.Prompt,"LibraryDescription": &op.LibraryDescription,"ApprovedDesign": &op.ApprovedDesign,"CompileExitCode": &op.CompileExitCode,"CompileStderr": &op.CompileStderr,"GoFilesOriginal": &op.GoFilesOriginal,"InitialBinPath": &op.InitialBinPath,"ValidationError": &op.ValidationError,
	}
}

func (op *FallbackOp) OutputFields() map[string]any {
	return map[string]any {
		"BinPath": &op.BinPath,"Stderr": &op.Stderr,
	}
}

func (op *FallbackOp) SetInputField(field string, value any) error {
	switch field {
	case "Prompt":
		if val, ok := value.(*string); ok {
			op.Prompt = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "LibraryDescription":
		if val, ok := value.(*string); ok {
			op.LibraryDescription = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "ApprovedDesign":
		if val, ok := value.(*string); ok {
			op.ApprovedDesign = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "CompileExitCode":
		if val, ok := value.(*int); ok {
			op.CompileExitCode = val
		} else {
			return fmt.Errorf("field %s is not type of *int", field)
		}
	case "CompileStderr":
		if val, ok := value.(*string); ok {
			op.CompileStderr = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "GoFilesOriginal":
		if val, ok := value.(*string); ok {
			op.GoFilesOriginal = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "InitialBinPath":
		if val, ok := value.(*string); ok {
			op.InitialBinPath = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "ValidationError":
		if val, ok := value.(*string); ok {
			op.ValidationError = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *FallbackOp) ResetFields() {
	var zeroPrompt *string
	op.Prompt = zeroPrompt
	var zeroLibraryDescription *string
	op.LibraryDescription = zeroLibraryDescription
	var zeroApprovedDesign *string
	op.ApprovedDesign = zeroApprovedDesign
	var zeroCompileExitCode *int
	op.CompileExitCode = zeroCompileExitCode
	var zeroCompileStderr *string
	op.CompileStderr = zeroCompileStderr
	var zeroGoFilesOriginal *string
	op.GoFilesOriginal = zeroGoFilesOriginal
	var zeroInitialBinPath *string
	op.InitialBinPath = zeroInitialBinPath
	var zeroValidationError *string
	op.ValidationError = zeroValidationError
	
	var zeroBinPath string
	op.BinPath = zeroBinPath
	var zeroStderr string
	op.Stderr = zeroStderr
	
}