// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *DAGDesignOp) InputFields() map[string]any {
	return map[string]any {
		"Prompt": &op.Prompt,"LibraryDescription": &op.LibraryDescription,
	}
}

func (op *DAGDesignOp) OutputFields() map[string]any {
	return map[string]any {
		"Design": &op.Design,
	}
}

func (op *DAGDesignOp) SetInputField(field string, value any) error {
	switch field {
	case "Prompt":
		if val, ok := value.(*string); ok {
			op.Prompt = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "LibraryDescription":
		if val, ok := value.(*string); ok {
			op.LibraryDescription = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *DAGDesignOp) ResetFields() {
	var zeroPrompt *string
	op.Prompt = zeroPrompt
	var zeroLibraryDescription *string
	op.LibraryDescription = zeroLibraryDescription
	
	var zeroDesign string
	op.Design = zeroDesign
	
}