// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *LibraryScanOp) InputFields() map[string]any {
	return map[string]any {
		
	}
}

func (op *LibraryScanOp) OutputFields() map[string]any {
	return map[string]any {
		"LibraryDescription": &op.LibraryDescription,
	}
}

func (op *LibraryScanOp) SetInputField(field string, value any) error {
	switch field {
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *LibraryScanOp) ResetFields() {
	
	var zeroLibraryDescription string
	op.LibraryDescription = zeroLibraryDescription
	
}