// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *MCPBManifestPromptOp) InputFields() map[string]any {
	return map[string]any {
		"Prompt": &op.Prompt,"BinPath": &op.BinPath,"RequiredEnvVars": &op.RequiredEnvVars,"DefaultName": &op.DefaultName,"DefaultDisplayName": &op.DefaultDisplayName,"DefaultDescription": &op.DefaultDescription,
	}
}

func (op *MCPBManifestPromptOp) OutputFields() map[string]any {
	return map[string]any {
		"Name": &op.Name,"DisplayName": &op.DisplayName,"Description": &op.Description,"Author": &op.Author,
	}
}

func (op *MCPBManifestPromptOp) SetInputField(field string, value any) error {
	switch field {
	case "Prompt":
		if val, ok := value.(*string); ok {
			op.Prompt = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "BinPath":
		if val, ok := value.(*string); ok {
			op.BinPath = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "RequiredEnvVars":
		if val, ok := value.(*string); ok {
			op.RequiredEnvVars = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "DefaultName":
		if val, ok := value.(*string); ok {
			op.DefaultName = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "DefaultDisplayName":
		if val, ok := value.(*string); ok {
			op.DefaultDisplayName = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "DefaultDescription":
		if val, ok := value.(*string); ok {
			op.DefaultDescription = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *MCPBManifestPromptOp) ResetFields() {
	var zeroPrompt *string
	op.Prompt = zeroPrompt
	var zeroBinPath *string
	op.BinPath = zeroBinPath
	var zeroRequiredEnvVars *string
	op.RequiredEnvVars = zeroRequiredEnvVars
	var zeroDefaultName *string
	op.DefaultName = zeroDefaultName
	var zeroDefaultDisplayName *string
	op.DefaultDisplayName = zeroDefaultDisplayName
	var zeroDefaultDescription *string
	op.DefaultDescription = zeroDefaultDescription
	
	var zeroName string
	op.Name = zeroName
	var zeroDisplayName string
	op.DisplayName = zeroDisplayName
	var zeroDescription string
	op.Description = zeroDescription
	var zeroAuthor string
	op.Author = zeroAuthor
	
}