// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *DAGDesignRefineOp) InputFields() map[string]any {
	return map[string]any {
		"Prompt": &op.Prompt,"LibraryDescription": &op.LibraryDescription,"PreviousDesign": &op.PreviousDesign,"Feedback": &op.Feedback,
	}
}

func (op *DAGDesignRefineOp) OutputFields() map[string]any {
	return map[string]any {
		"Design": &op.Design,
	}
}

func (op *DAGDesignRefineOp) SetInputField(field string, value any) error {
	switch field {
	case "Prompt":
		if val, ok := value.(*string); ok {
			op.Prompt = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "LibraryDescription":
		if val, ok := value.(*string); ok {
			op.LibraryDescription = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "PreviousDesign":
		if val, ok := value.(*string); ok {
			op.PreviousDesign = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "Feedback":
		if val, ok := value.(*string); ok {
			op.Feedback = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *DAGDesignRefineOp) ResetFields() {
	var zeroPrompt *string
	op.Prompt = zeroPrompt
	var zeroLibraryDescription *string
	op.LibraryDescription = zeroLibraryDescription
	var zeroPreviousDesign *string
	op.PreviousDesign = zeroPreviousDesign
	var zeroFeedback *string
	op.Feedback = zeroFeedback
	
	var zeroDesign string
	op.Design = zeroDesign
	
}