// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *PromptOp) InputFields() map[string]any {
	return map[string]any {
		
	}
}

func (op *PromptOp) OutputFields() map[string]any {
	return map[string]any {
		"Prompt": &op.Prompt,
	}
}

func (op *PromptOp) SetInputField(field string, value any) error {
	switch field {
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *PromptOp) ResetFields() {
	
	var zeroPrompt string
	op.Prompt = zeroPrompt
	
}