// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *GenerateOp) InputFields() map[string]any {
	return map[string]any {
		"Prompt": &op.Prompt,"LibraryDescription": &op.LibraryDescription,"ApprovedDesign": &op.ApprovedDesign,
	}
}

func (op *GenerateOp) OutputFields() map[string]any {
	return map[string]any {
		"GoFiles": &op.GoFiles,
	}
}

func (op *GenerateOp) SetInputField(field string, value any) error {
	switch field {
	case "Prompt":
		if val, ok := value.(*string); ok {
			op.Prompt = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "LibraryDescription":
		if val, ok := value.(*string); ok {
			op.LibraryDescription = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "ApprovedDesign":
		if val, ok := value.(*string); ok {
			op.ApprovedDesign = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *GenerateOp) ResetFields() {
	var zeroPrompt *string
	op.Prompt = zeroPrompt
	var zeroLibraryDescription *string
	op.LibraryDescription = zeroLibraryDescription
	var zeroApprovedDesign *string
	op.ApprovedDesign = zeroApprovedDesign
	
	var zeroGoFiles string
	op.GoFiles = zeroGoFiles
	
}