// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *PackageMCPBOp) InputFields() map[string]any {
	return map[string]any {
		"BinPath": &op.BinPath,"Name": &op.Name,"DisplayName": &op.DisplayName,"Description": &op.Description,"Author": &op.Author,"RequiredEnvVars": &op.RequiredEnvVars,
	}
}

func (op *PackageMCPBOp) OutputFields() map[string]any {
	return map[string]any {
		"MCPBPath": &op.MCPBPath,
	}
}

func (op *PackageMCPBOp) SetInputField(field string, value any) error {
	switch field {
	case "BinPath":
		if val, ok := value.(*string); ok {
			op.BinPath = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "Name":
		if val, ok := value.(*string); ok {
			op.Name = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "DisplayName":
		if val, ok := value.(*string); ok {
			op.DisplayName = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "Description":
		if val, ok := value.(*string); ok {
			op.Description = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "Author":
		if val, ok := value.(*string); ok {
			op.Author = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "RequiredEnvVars":
		if val, ok := value.(*string); ok {
			op.RequiredEnvVars = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *PackageMCPBOp) ResetFields() {
	var zeroBinPath *string
	op.BinPath = zeroBinPath
	var zeroName *string
	op.Name = zeroName
	var zeroDisplayName *string
	op.DisplayName = zeroDisplayName
	var zeroDescription *string
	op.Description = zeroDescription
	var zeroAuthor *string
	op.Author = zeroAuthor
	var zeroRequiredEnvVars *string
	op.RequiredEnvVars = zeroRequiredEnvVars
	
	var zeroMCPBPath string
	op.MCPBPath = zeroMCPBPath
	
}