// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *WriteFilesOp) InputFields() map[string]any {
	return map[string]any {
		"GoFiles": &op.GoFiles,
	}
}

func (op *WriteFilesOp) OutputFields() map[string]any {
	return map[string]any {
		"TempDir": &op.TempDir,
	}
}

func (op *WriteFilesOp) SetInputField(field string, value any) error {
	switch field {
	case "GoFiles":
		if val, ok := value.(*string); ok {
			op.GoFiles = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *WriteFilesOp) ResetFields() {
	var zeroGoFiles *string
	op.GoFiles = zeroGoFiles
	
	var zeroTempDir string
	op.TempDir = zeroTempDir
	
}