// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *OutputOp) InputFields() map[string]any {
	return map[string]any {
		"RawStdout": &op.RawStdout,"RawStderr": &op.RawStderr,"ExitCode": &op.ExitCode,
	}
}

func (op *OutputOp) OutputFields() map[string]any {
	return map[string]any {
		"Result": &op.Result,"AINodes": &op.AINodes,"ErrorMsg": &op.ErrorMsg,
	}
}

func (op *OutputOp) SetInputField(field string, value any) error {
	switch field {
	case "RawStdout":
		if val, ok := value.(*string); ok {
			op.RawStdout = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "RawStderr":
		if val, ok := value.(*string); ok {
			op.RawStderr = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "ExitCode":
		if val, ok := value.(*int); ok {
			op.ExitCode = val
		} else {
			return fmt.Errorf("field %s is not type of *int", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *OutputOp) ResetFields() {
	var zeroRawStdout *string
	op.RawStdout = zeroRawStdout
	var zeroRawStderr *string
	op.RawStderr = zeroRawStderr
	var zeroExitCode *int
	op.ExitCode = zeroExitCode
	
	var zeroResult string
	op.Result = zeroResult
	var zeroAINodes string
	op.AINodes = zeroAINodes
	var zeroErrorMsg string
	op.ErrorMsg = zeroErrorMsg
	
}