// Code generated by daggen. DO NOT EDIT.
package main

import (
	"fmt"
)

func (op *RunOp) InputFields() map[string]any {
	return map[string]any {
		"BinPath": &op.BinPath,"CompileStderr": &op.CompileStderr,
	}
}

func (op *RunOp) OutputFields() map[string]any {
	return map[string]any {
		"Stdout": &op.Stdout,"Stderr": &op.Stderr,"ExitCode": &op.ExitCode,
	}
}

func (op *RunOp) SetInputField(field string, value any) error {
	switch field {
	case "BinPath":
		if val, ok := value.(*string); ok {
			op.BinPath = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	case "CompileStderr":
		if val, ok := value.(*string); ok {
			op.CompileStderr = val
		} else {
			return fmt.Errorf("field %s is not type of *string", field)
		}
	
	default:
		return fmt.Errorf("field %s is not defined", field)
	}
	return nil
}

func (op *RunOp) ResetFields() {
	var zeroBinPath *string
	op.BinPath = zeroBinPath
	var zeroCompileStderr *string
	op.CompileStderr = zeroCompileStderr
	
	var zeroStdout string
	op.Stdout = zeroStdout
	var zeroStderr string
	op.Stderr = zeroStderr
	var zeroExitCode int
	op.ExitCode = zeroExitCode
	
}